# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01d083ce4f8b657c6b44f7cd70be4a51b16887aa705f3fdef3064477354fe68debdc4a38f3a4ba28173d5e81b2a392f100e0cd6f15bd130cec28f38b88f34eb0

test:
  secret_key_base: 4bb11d3998365f1c43f6053f91126c40db9797722ec221363e38947bd94b16a567a1a043a115664d0e8e42749a9d2f0e4db7666e690e1c1d67d2773e96a03bdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
